CREATE TABLE IF NOT EXISTS attendance_fact (
    attendance_id       BIGINT,
    check_in_epoch            BIGINT,
    check_out_epoch           BIGINT,
    company_id          BIGINT,
    schedule_id         BIGINT,
    schedule_date_epoch       BIGINT,
    clock_in_time_sec       Int32,
    clock_out_time_sec      Int32,
    shift_rule_id       BIGINT,
    shift_rule_name     String,
    location_address    String,
    location_name       String,
    sr_cit_sec              Int32,
    sr_cot_sec              Int32,
    user_id             BIGINT,
    nip                 String,
    fullname            String,
    unor_id             Int32,
    unit_organisasi     String,
    parent_id           BIGINT,
    grade_id            BIGINT,
    grade_name          String,
    nama_jabatan        String,
    position_type_id    Int32,
    jenis_jabatan       String,
	is_deleted          UInt8 -- auto filled by Risingwave when deletion happens
) ENGINE = ReplacingMergeTree(is_deleted)
ORDER BY (attendance_id);