CREATE TABLE NOT EXISTS attendance_fact (
    attendance_id       BIGINT,
    check_in            DateTime,
    check_out           DateTime,
    company_id          BIGINT,
    schedule_id         BIGINT,
    schedule_date       Date,
    clock_in_time       String,
    clock_out_time      String,
    shift_rule_id       BIGINT,
    shift_rule_name     String,
    location_address    String,
    location_name       String,
    sr_cit              String,
    sr_cot              String,
    user_id             BIGINT,
    nip                 String,
    fullname            String,
    unor_id             BIGINT,
    unit_organisasi     String,
    parent_id           BIGINT,
    grade_id            BIGINT,
    grade_name          String,
    nama_jabatan        String,
    position_type_id    BIGINT,
    jenis_jabatan       String,
	is_deleted          UInt8 -- auto filled by Risingwave when deletion happens
) ENGINE = ReplacingMergeTree(is_deleted)
ORDER BY (attendance_id);