CREATE TABLE IF NOT EXISTS attendance_fact (
    attendance_id       BIGINT,
    check_in_epoch      BIGINT,
    check_out_epoch     Nullable(BIGINT),
    company_id          BIGINT,
    schedule_id         BIGINT,
    schedule_date_epoch BIGINT,
    clock_in_time_sec   Nullable(Int32),
    clock_out_time_sec  Nullable(Int32),
    shift_rule_id       BIGINT,
    shift_rule_name     Nullable(String),
    location_address    Nullable(String),
    location_name       Nullable(String),
    sr_cit_sec          Nullable(Int32),
    sr_cot_sec          Nullable(Int32),
    user_id             BIGINT,
    nip                 Nullable(String),
    fullname            Nullable(String),
    unor_id             Nullable(Int32),
    unit_organisasi     Nullable(String),
    parent_id           Nullable(BIGINT),
    grade_id            Nullable(BIGINT),
    grade_name          Nullable(String),
    nama_jabatan        Nullable(String),
    position_type_id    Nullable(Int32),
    jenis_jabatan       Nullable(String),
	is_deleted          UInt8 -- auto filled by Risingwave when deletion happens
) ENGINE = ReplacingMergeTree(is_deleted)
ORDER BY (attendance_id);